services:
  my_love_backend:
    container_name: my_love_backend
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - my_love_database
    networks:
      - my_love_application_net

  my_love_database:
    image: postgres:17
    container_name: my_love_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_love_application_net

  my_love_redis:
    image: redis:7-alpine
    container_name: my_love_redis
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      redis-server
      --requirepass $${REDIS_PASSWORD}
      --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - my_love_application_net
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:

networks:
  my_love_application_net:
    driver: bridge
