services:
  my-love-backend:
    container_name: my-love-backend
    build: .
    environment:
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - my-love-database
      - my-love-redis
      - my-love-minio
    networks:
      - my-love-application-net

  my-love-database:
    image: postgres:17
    container_name: my-love-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-love-application-net

  my-love-redis:
    image: redis:7-alpine
    container_name: my-love-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    networks:
      - my-love-application-net
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: unless-stopped

  my-love-minio:
    image: minio/minio
    container_name: my-love-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - my-love-application-net
    command: server --console-address ":9001" /data

volumes:
  pgdata:
  redis_data:
  minio_data:


networks:
  my-love-application-net:
    driver: bridge
