services:
  my-love-backend:
    container_name: my-love-backend
    build: .
    environment:
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      my-love-database:
        condition: service_healthy
      my-love-redis:
        condition: service_healthy
      my-love-minio:
        condition: service_healthy
    networks:
      - my-love-application-net
    restart: unless-stopped

  my-love-database:
    image: postgres:17
    container_name: my-love-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-love-application-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  my-love-redis:
    image: redis:7-alpine
    container_name: my-love-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    networks:
      - my-love-application-net
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  my-love-minio:
    image: minio/minio
    container_name: my-love-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - my-love-application-net
    command: server --console-address ":9001" /data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 5

volumes:
  pgdata:
  redis_data:
  minio_data:


networks:
  my-love-application-net:
    driver: bridge
